name: picker
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.5
  pin_code_fields: ^7.3.0
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  geolocator: ^8.2.0
  syncfusion_flutter_charts: ^19.4.54
  syncfusion_flutter_datepicker: ^19.4.54
  syncfusion_localizations: ^19.4.55
  dart_extensions: ^2.0.0
  flutter_native_splash: ^2.1.0
  onesignal_flutter: ^3.0.0
  shared_preferences: ^2.0.7
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  retry: ^3.1.0
  equatable: ^2.0.3
  http: ^0.13.3
  connectivity: ^3.0.6
  yaml: ^3.1.0
  cached_network_image: ^3.1.0
  slide_to_confirm: ^1.1.0
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:

  android: true # show for android, you may set it to false
  ios: true # show for IOS, you may set it to false

  image: assets/images/splash.png # the default image for light and dark themes. Until now, images should be png images
  image_dark: assets/images/splash.png # It will override the 'image' in the dark mode

  color: "#ffffff" # the default color for light and dark themes
  color_dark: "#ffffff" # will override the 'color' in the dark mode

  android_gravity: center # make the image fill the screen for android
  ios_content_mode: center
  # fullscreen: true

  android_12:
    # The image parameter sets the splash screen icon image.  If this parameter is not specified,
    # the app's launcher icon will be used instead.
    # Please note that the splash screen will be clipped to a circle on the center of the screen.
    # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
    # 640 pixels in diameter.
    # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
    # 768 pixels in diameter.
    image: assets/images/splash.png

    # App icon background color.
    icon_background_color: "#ffffff"

    # The image_dark parameter and icon_background_color_dark set the image and icon background
    # color when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    image_dark: assets/images/splash.png
    icon_background_color_dark: "#ffffff"

# The following section is specific to Flutter.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - pubspec.yaml
    - mock_data/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf