import 'package:flutter_svg/flutter_svg.dart';
import 'package:picker/constants/constants.dart';

class PreCacheSvg {
  const PreCacheSvg._();

  static Future<void> preCacheLoadSvg() async {
    await Future.wait([
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.appLogo.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.bgOrderHistoryEmpty.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.closeIcon.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.hamburger.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.circleClearText.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.close.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.dropDown.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.exit.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.lock.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.navBack.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.navRight.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.noteList.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.notification.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.orderCancelled.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.orderCompleted.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.orderMissed.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.printer.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.orderSection.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.pickerStatus.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.productSection.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.productivitySection.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.redArrow.toAssetName(),
        ),
        null,
      ),
      precachePicture(
        ExactAssetPicture(
          SvgPicture.svgStringDecoderBuilder,
          AppIcons.warning.toAssetName(),
        ),
        null,
      ),
    ]);
  }
}
